jobs:
  - name: run-pipeline
    job:
      type: decision-task
      # we don't use treeherder...but this is a required field
      treeherder-symbol: pipeline
      target-tasks-method: train-target-tasks
